package com.cquilez.pitesthelper.infrastructure.service.buildunit

import com.cquilez.pitesthelper.domain.BuildSystem
import com.cquilez.pitesthelper.domain.BuildUnit
import com.cquilez.pitesthelper.domain.CodeType
import com.cquilez.pitesthelper.domain.SourceFolder
import com.cquilez.pitesthelper.infrastructure.adapter.buildunit.AbstractBuildUnitServiceAdapter
import com.cquilez.pitesthelper.infrastructure.service.sourcefolder.SourceFolderService
import com.intellij.openapi.components.service
import com.intellij.openapi.module.Module
import com.intellij.openapi.module.ModuleManager
import com.intellij.openapi.project.Project
import com.intellij.openapi.roots.ModuleRootManager
import kotlinx.collections.immutable.toImmutableSet
import org.jetbrains.jps.model.java.JavaSourceRootType
import java.nio.file.Path
import kotlin.io.path.Path

private data class GradleBuildFileInfo(
    val buildSystem: BuildSystem,
    val buildPath: Path,
    val buildFileName: String,
    val sourceFolders: List<SourceFolder>
)

class GradleBuildUnitService : AbstractBuildUnitServiceAdapter() {

    override fun getBuildSystem(): BuildSystem = BuildSystem.GRADLE

    override fun scanBuildUnits(project: Project): List<BuildUnit> {
        val sourceFolderService = project.service<SourceFolderService>()
        val allModules = ModuleManager.getInstance(project).modules.toList()
        val buildFileInfoList = detectAllBuildFiles(allModules, sourceFolderService)
        return buildHierarchyFromBottomToTop(buildFileInfoList)
    }

    private fun detectAllBuildFiles(
        allModules: List<Module>,
        sourceFolderService: SourceFolderService
    ): List<GradleBuildFileInfo> {
        // First pass: detect all build unit directories
        val buildFileLocations =
            mutableMapOf<Path, Pair<Path, String>>() // buildUnitDir -> (buildFilePath, buildFileName)

        for (module in allModules) {
            val contentRoots = ModuleRootManager.getInstance(module).contentRoots

            for (contentRoot in contentRoots) {
                val buildFile = contentRoot.findChild("build.gradle.kts")
                    ?: contentRoot.findChild("build.gradle")
                    ?: contentRoot.findChild("settings.gradle.kts")
                    ?: contentRoot.findChild("settings.gradle")

                if (buildFile != null && buildFile.exists()) {
                    val buildFilePath = Path(buildFile.path)
                    val buildUnitDir = buildFilePath.parent
                    buildFileLocations[buildUnitDir] = Pair(buildFilePath, buildFile.name)
                }
            }
        }

        // Second pass: for each build unit, find source folders excluding nested build unit directories
        val allBuildUnitDirs = buildFileLocations.keys.toImmutableSet()
        return buildFileLocations.map { (buildUnitDir, buildFileInfo) ->
            val (buildFilePath, buildFileName) = buildFileInfo
            val nestedBuildUnitDirs = allBuildUnitDirs.filter { otherDir ->
                otherDir != buildUnitDir && otherDir.startsWith(buildUnitDir)
            }.toSet()

            val sourceFolders = findSourceFoldersInRelatedModules(
                buildUnitDir,
                nestedBuildUnitDirs,
                allModules,
                sourceFolderService
            )
            GradleBuildFileInfo(BuildSystem.GRADLE, buildFilePath, buildFileName, sourceFolders)
        }
    }

    /**
     * In Gradle projects, IntelliJ creates separate modules for the build file location,
     * src/main, and src/test. This method finds all source folders from all modules
     * whose content roots are within the build unit directory, excluding source folders
     * that belong to nested build units.
     */
    private fun findSourceFoldersInRelatedModules(
        buildUnitDir: Path,
        nestedBuildUnitDirs: Set<Path>,
        allModules: List<Module>,
        sourceFolderService: SourceFolderService
    ): List<SourceFolder> {
        val sourceFolders = mutableListOf<SourceFolder>()

        for (module in allModules) {
            val moduleRootManager = ModuleRootManager.getInstance(module)

            for (contentEntry in moduleRootManager.contentEntries) {
                val contentRootPath = contentEntry.file?.path?.let { Path(it) } ?: continue

                // Check if this module's content root is within the build unit directory
                // but NOT within any nested build unit directory
                val isWithinBuildUnit = contentRootPath.startsWith(buildUnitDir)
                val isWithinNestedBuildUnit = nestedBuildUnitDirs.any { contentRootPath.startsWith(it) }

                if (isWithinBuildUnit && !isWithinNestedBuildUnit) {
                    contentEntry.sourceFolders
                        .filter { it.rootType is JavaSourceRootType }
                        .filter { !sourceFolderService.isAutogeneratedSourceFolder(it) }
                        .forEach { intellijSourceFolder ->
                            val virtualFile = intellijSourceFolder.file
                            if (virtualFile != null) {
                                val sourceFolderPath = Path(virtualFile.path)

                                val codeType = if (intellijSourceFolder.rootType.isForTests) {
                                    CodeType.TEST
                                } else {
                                    CodeType.PRODUCTION
                                }

                                sourceFolders.add(
                                    SourceFolder(
                                        path = sourceFolderPath,
                                        codeType = codeType
                                    )
                                )
                            }
                        }
                }
            }
        }

        return sourceFolders.distinct()
    }

    private fun buildHierarchyFromBottomToTop(buildFileInfoList: List<GradleBuildFileInfo>): List<BuildUnit> {
        if (buildFileInfoList.isEmpty()) return emptyList()

        val sortedByDepthDescending = buildFileInfoList.sortedByDescending { info ->
            info.buildPath.parent.nameCount
        }

        val childrenMap = buildChildrenMap(sortedByDepthDescending)

        // Collect all child build paths to identify root build units
        val childBuildPaths = childrenMap.values.flatten().map { it.buildPath }.toSet()

        val buildUnitMap = mutableMapOf<Path, BuildUnit>()

        for (buildFileInfo in sortedByDepthDescending) {
            val childBuildUnits = childrenMap[buildFileInfo.buildPath]
                ?.mapNotNull { buildUnitMap[it.buildPath] }
                ?: emptyList()

            val buildUnit = BuildUnit(
                name = buildFileInfo.buildPath.parent.fileName.toString(),
                buildSystem = buildFileInfo.buildSystem,
                buildPath = buildFileInfo.buildPath,
                sourceFolders = buildFileInfo.sourceFolders,
                buildUnits = childBuildUnits
            )

            buildUnitMap[buildFileInfo.buildPath] = buildUnit
        }

        // Return only root build units (those that are not children of any other build unit)
        return sortedByDepthDescending
            .filter { it.buildPath !in childBuildPaths }
            .mapNotNull { buildUnitMap[it.buildPath] }
    }

    private fun buildChildrenMap(sortedByDepthDescending: List<GradleBuildFileInfo>): Map<Path, MutableList<GradleBuildFileInfo>> {
        val childrenMap = mutableMapOf<Path, MutableList<GradleBuildFileInfo>>()

        for (child in sortedByDepthDescending) {
            val childDir = child.buildPath.parent
            var immediateParent: GradleBuildFileInfo? = null

            for (potentialParent in sortedByDepthDescending) {
                if (potentialParent == child) continue
                val parentDir = potentialParent.buildPath.parent

                if (childDir.startsWith(parentDir) && childDir != parentDir
                    && (immediateParent == null || immediateParent.buildPath.parent.nameCount < parentDir.nameCount)
                ) {
                    immediateParent = potentialParent
                }
            }

            if (immediateParent != null) {
                childrenMap.getOrPut(immediateParent.buildPath) { mutableListOf() }.add(child)
            }
        }
        return childrenMap
    }
}
