package com.cquilez.pitesthelper.infrastructure.service

import com.intellij.openapi.components.Service
import com.intellij.openapi.components.service
import com.intellij.openapi.project.Project
import com.intellij.openapi.roots.SourceFolder
import org.jetbrains.jps.model.java.JavaSourceRootProperties
import java.nio.file.Path

@Service(Service.Level.PROJECT)
class SourceFolderService(project: Project) {

    private val cacheService = project.service<CacheService>()

    fun isPathSourceFolder(path: Path): Boolean {
        return cacheService.sourceFolderCache.containsKey(path)
    }

    fun isAutogeneratedSourceFolder(sourceFolder: SourceFolder): Boolean {
        val properties = sourceFolder.jpsElement.properties
        if (properties is JavaSourceRootProperties) {
            return properties.isForGeneratedSources
        }
        return false
    }
}